spring:
  datasource:
    password: marcio
    username: postgres
    url: jdbc:postgresql://localhost:5432/curso-dev-eficiente
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: casadocodigo
  application:
    name: apicasadocodigo
        
server:
  port: 8080
  servlet:
    context-path: /apicasadocodigo